# Metadata Queries
- 
  path: 'sql/metadata/load_tables.sql'
  runner: create_local_table_athena
  name: load_metadata_tables

- 
  path: 'sql/metadata/'
  runner: create_local_table_athena
  depends_on: [
    load_metadata_tables
  ]
  name: metadata_prepare
  mode: overwrite

- 
  path: 'sql/metadata/'
  runner: create_local_table_athena
  depends_on: [
    metadata_prepare
  ]
  name: metadata_osm_length
  mode: overwrite_partitions

- 
  path: 'sql/metadata/create-metadata-ready.sql'
  runner: basic_athena_query
  depends_on: [
    metadata_osm_length
    ]
  name: metadata_ready

# Analysis
- 
  path: 'sql/analysis/create_dummy_year.sql'
  runner: create_local_table_athena
  name: dummy_2019
  year: 2019


- 
  path: 'sql/analysis/create-daily-table'
  runner: partitioned_athena_query
  depends_on: [
    metadata_ready
  ]
  name: analysis_daily
  year: 2019
  if_exists: 'append'
  current_millis: 'fixed4'
  sampled: ['country_brazil', 'country_mexico'] 
  year: 2019

- 
  path: 'sql/analysis/add_variation_to_metadata.sql'
  runner: basic_athena_query
  depends_on: [
    analysis_daily,
    metadata_ready
  ]
  name: metadata_variation


# Daily Queries
- 
  path: 'sql/daily/create-filtered-table'
  runner: partitioned_athena_query
  name: daily
  depends_on: [
    metadata_variation
  ]
  current_millis: v7
  daily_aggregation:  year%Ymonth%m # 'year%Yweek%W' # year%Yday%m%d
  mode: 'incremental'
  interval:
    start: 2020-03-09
    end: 'today'
 

- 
  path: 'sql/daily/create-filtered-table'
  runner: partitioned_athena_query
  name: historical_2019
  depends_on: [
    historical_2019_raw, 
    metadata_variation
  ]
  current_millis: v6
  daily_aggregation:  year%Ymonth%m # 'year%Yweek%W' # year%Yday%m%d
  mode: 'incremental'
  interval:
    start: 2019-03-09
    end: 2019-03-31


- 
  path: 'sql/daily/create-filtered-table'
  runner: partitioned_athena_query
  name: historical_2020
  depends_on: [
    historical_2020_raw, 
    metadata_variation
  ]
  current_millis: v6
  daily_aggregation:  year%Ymonth%m # 'year%Yweek%W' # year%Yday%m%d
  mode: 'incremental'
  interval:
    start: 2020-03-01
    end: 2020-03-08


- 
  path: 'sql/daily/create-daily-index-table.sql'
  runner: basic_athena_query
  depends_on: [
    metadata_variation,
    daily,
    historical_2019,
    historical_2020
  ]
  name: daily_index
  force: True
  
- 
  path: 'sql/daily/create-weekly-index-table.sql'
  runner: basic_athena_query
  depends_on: [
    metadata_variation,
    daily,
    historical_2019,
    historical_2020
  ]
  name: weekly_index

- 
  path: 'sql/daily/create-hourly-index-table.sql'
  runner: basic_athena_query
  depends_on: [
    metadata_variation,
    daily,
    historical_2019,
    historical_2020
  ]
  name: hourly_index

- 
  path: 'sql/daily/create-grouphours-index-table.sql'
  runner: basic_athena_query
  depends_on: [
    metadata_variation,
    daily,
    historical_2019,
    historical_2020
  ]
  name: grouphours_index
- 
  path: 'sql/daily/'
  runner: create_local_table_athena
  depends_on: [
    weekly_index,
    daily_index,
    hourly_index
  ]
  name: write_index
  to_write: 
    - table: daily_daily_index
      worksheet: daily
      overall_drop: [region_shapefile_wkt]
      public_drop: ['observed', 'expected_2019', 'expected_2020', 'dashboard', 'ratio_19']
    - table: daily_weekly_index
      worksheet: weekly
      overall_drop: [region_shapefile_wkt]
      public_drop: ['observed', 'expected_2019', 'expected_2020', 'dashboard', 'ratio_19']
    - table: analysis_metadata_variation
      worksheet: metadata
      overall_drop: ['region_shapefile_binary', 'area']
      public_drop: ['daily_mean', 'weekly_mean', 'daily_std', 'weekly_std', 
                   'daily_osm_ratio', 'weekly_osm_ratio', 'dashboard', 'rerun',
                   'waze_code', 'idb_code', 'country_name_idb_eng', 'n_days',
                   'daily_mean_weekend', 'daily_std_weekend', 'daily_mean_weekday',
                   'daily_std_weekday']
    - table: daily_grouphours_index
      worksheet: grouphours
      overall_drop: []
      public_drop: []

# GRID
- 
  path: 'sql/grid/'
  runner: region_grid
  depends_on: [
    metadata_variation
  ]
  mode: overwrite
  name: resolutions
  coarse_resolutions: 7
  granular_resolution: 10


- 
  path: 'sql/grid/create-coarse-grid/'
  runner: region_grid
  depends_on: [
    resolutions,
    daily
  ]
  name: coarse
  from_table: daily_daily


- 
  path: 'sql/grid/create-grid'
  runner: partitioned_athena_query
  depends_on: [
    resolutions,
    coarse
  ]
  name: grid


- 
  path: 'sql/grid/create-coarse-grid/'
  runner: region_grid
  depends_on: [
    resolutions,
    daily_historical_2020
  ]
  name: coarse_2020
  from_table: daily_historical_2020


- 
  path: 'sql/grid/create-grid'
  runner: partitioned_athena_query
  depends_on: [
    resolutions,
    coarse_2020
  ]
  name: grid_2020


- 
  path: 'sql/grid/create-hourly-index.sql'
  runner: basic_athena_query
  depends_on: [
    grid,
    grid_2020,
    metadata_variation
  ]
  name: grid_hourly_index
  force: True

# Cities
- 
  path: 'sql/cities/'
  runner: all_cities
  depends_on: [
    metadata_variation
  ]
  mode: overwrite
  name: country_resolutions
  coarse_resolutions: 3
  jobs:
    - region_slug: country_chile
      file: chile_comunas.csv

    # - region_slug: country_brazil
    #   file: brazil_cities.csv

- 
  path: 'sql/cities/create-coarse-grid'
  runner: all_cities
  depends_on: [
    daily_daily
    country_resolutions
  ]
  name: country_coarse
  from_table: daily_daily

- 
  path: 'sql/cities/create-grid'
  runner: partitioned_athena_query
  depends_on: [
    country_resolutions,
    country_coarse
  ]
  from_table: country_coarse
  name: country_cities
  

- 
  path: 'sql/cities/create-coarse-grid'
  runner: all_cities
  depends_on: [
    daily_historical_2020,
    country_resolutions
  ]
  name: country_coarse_2020
  from_table: daily_historical_2020
  
- 
  path: 'sql/cities/create-grid'
  runner: partitioned_athena_query
  depends_on: [
    country_resolutions,
    country_coarse_2020
  ]
  from_table: country_coarse_2020
  name: country_cities_2020
  

- 
  path: 'sql/cities/create-hourly-index.sql'
  runner: basic_athena_query
  depends_on: [
    country_cities,
    country_cities_2020,
  ]
  name: country_cities_hourly_index
  
- 
  path: 'sql/cities/create-daily-index.sql'
  runner: basic_athena_query
  depends_on: [
    country_cities,
    country_cities_2020,
  ]
  name: country_cities_daily_index

- 
  path: 'sql/cities/create-weekly-index.sql'
  runner: basic_athena_query
  depends_on: [
    country_cities,
    country_cities_2020,
  ]
  name: country_cities_weekly_index
  
- 
  path: 'sql/daily/create-filtered-table'
  runner: partitioned_athena_query
  name: sample_2019
  depends_on: [
    metadata_variation
  ]
  current_millis: v2
  daily_aggregation:  year%Y # 'year%Yweek%W' # year%Yday%m%d
  mode: 'incremental'
  selected_regions: [country_chile]
  interval:
    start: 2019-01-01
    end: 2019-12-31

  

- 
  path: 'sql/cities/create-coarse-grid'
  runner: all_cities
  depends_on: [
    sample_2019
    country_resolutions
  ]
  name: country_coarse_2019
  from_table: daily_sample_2019

  
- 
  path: 'sql/cities/create-grid'
  runner: partitioned_athena_query
  depends_on: [
    country_resolutions,
    country_coarse_2019
  ]
  name: country_cities_2019
  from_table: country_coarse_2019