# Historical Queries
- 
  path: 'sql/historical/create-historical-raw-table.sql'
  runner: basic_athena_query
  name: historical_2019_raw

- 
  path: 'sql/historical/create-historical-raw-table.sql'
  runner: basic_athena_query
  name: historical_2020_raw

# Metadata Queries

- 
  path: 'sql/metadata/load_tables.sql'
  runner: create_local_table_athena
  name: load_metadata_tables
  force: True


- 
  path: 'sql/metadata/create-metadata-ready.sql'
  runner: basic_athena_query
  depends_on: [
    load_metadata_tables
  ]
  name: metadata_ready
  force: True

# Daily Queries
- 
  path: 'sql/daily/create-daily-raw-table.sql'
  runner: basic_athena_query
  name: daily_raw

- 
  path: 'sql/daily/create-historical-table'
  runner: partitioned_athena_query
  name: historical_2019
  depends_on: [
    historical_2019_raw,
    metadata_ready
  ]
  year: 2019

- 
  path: 'sql/daily/create-historical-table'
  runner: partitioned_athena_query
  name: historical_2020
  depends_on: [
    historical_2020_raw,
    metadata_ready
  ]
  year: 2020
  force: True

- 
  path: 'sql/daily/create-daily-table'
  runner: partitioned_athena_query
  depends_on: [
    daily_raw,
    metadata_ready
  ]
  name: daily
  force: True

- 
  path: 'sql/daily/create-index-table.sql'
  runner: basic_athena_query
  depends_on: [
    metadata_ready,
    daily,
    historical_2019,
    historical_2020
  ]
  name: index


- 
  path: 'sql/daily/'
  runner: create_local_table_athena
  depends_on: [
    index
  ]
  name: write_index
