write_index:
    dev: 
        spreadsheet_key: 1XifbMbgr8KsIZW4dgvEO8MC7bLQPJHcFEdlcHR6puW0
    prod: 
        spreadsheet_key: 1xBDV5Zm7zSRPK2TGBoVSHhkvPeqRT9hZFiD4AueoVeI
    public:
        spreadsheet_key: 16SIYidLScgFZOeqpHmAo_u_rFmuxxpCCWeRAXSDOT3I

write_analysis_daily:
    analysis:
        spreadsheet_key: 17HziErk59RAQOKBJSq51FV6reJ2PekF0Mf3fTabEYEU
        worksheet: main
    dev:
        spreadsheet_key: 17HziErk59RAQOKBJSq51FV6reJ2PekF0Mf3fTabEYEU
        worksheet: main